_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    CLS_LOSS_TYPE : 'bnrl_loss'
    ALPHA : 0.2
    EPSILON : 1.0
    GAMMA : 4.0
    BG_WEIGHT : 0.2 
DATASETS:
  TRAIN: ('coco14_trainval_all_10shot_seed0',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (4800,)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  CMCLIP_ALPHA : 0.7
  CMCLIP_ENABLE: True
OUTPUT_DIR: "/Path/to/Output/Dir"