_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 5
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    CLS_LOSS_TYPE : 'bnrl_loss'
    ALPHA : 0.2
    EPSILON : 1.0
    GAMMA : 4.0
    BG_WEIGHT : 0.2 
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novel1_10shot_seed0", )
  TEST: ('voc_2007_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (3200, )
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  CMCLIP_ALPHA : 0.7
  CMCLIP_ENABLE: True
  CMCLIP_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"